name: Checkmarx One Scan on PushAdd commentMore actions
on:
  workflow_dispatch:

jobs:
  security-scans:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkmarx AST Github Action
        # You may pin to the exact commit or the version.
        # uses: Checkmarx/ast-github-action@749fec53e0db0f6404a97e2e0807c3e80e3583a7
        uses: Checkmarx/ast-github-action@2.0.23
        with:
          # Provide the AST portal URL
          base_uri: https://github.com/cx-devsecops/dvwa
          # Provide the Tenant for AST portal URL
          cx_tenant: https://us.ast.checkmarx.net
          # Client ID for AST portal authentication
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          # Secret key for AST portal authentication
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          # Select a Checkmarx Project Name
          project_name: ${{ github.repository }}
          # Branch name
          branch: ${{ github.ref }}
          # Repository name for PR decoration
          repo_name: ${{ github.event.repository.name }}
          # Organization name to create the Pr comment
          namespace: ${{ github.repository_owner }}
          # Pr Number of the pull request that needs the decoration
          pr_number: ${{ github.event.number }}
      
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: cx_result.sarif